# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#مرحبا بك في جيكل!
# ملف الكونفج/الإعدادات هذا معني بالإعدادات التي تأثر على المدونة ككل,
# المتغيرات التي من المتوقع منك ان تقوم بإعدادها عند إستعمالك لأول مرة و نادراً ما ستحتاج ان تعدل عليها بعد ذلك
# لأجل اسباب تقنية, هذا الملف *لن* يتم إعادة بناءة اوتوماتيكياً عندما تستخدم 'jekyll serve' اذا قمت بتعديل هذا الملف, الرجاء أعد تشغيل السيرفر او قم بإعادة بناءة عن طريق 'jekyll build'.





# إعدادات الموقع
#أكتب هنا اسم الموقع
title: جيكل العربي 
#أكتب هنا الإيميل الخاص بك/الموقع
email: binaryminded@gmail.com 
#أكتب شرح رائع عن موقعك هنا. سوف يظهر في (head meta) الخاص بمستندك (من اجل نتائج بحث قووقل) و في شرح موقعك في ملف feed.xml

description: > # this means to ignore newlines until "baseurl:" 
 تم إنشاء هذا جيكل العربي لمساعدة الأخوة العرب على الإستعمال السريع لجيكل دون الحاجة للقيام بالكثير من التغييرات.
 Jekyll Arabic was made to help fellow Arabs to quickly dive into Jekyll without the need to make many changes.
baseurl: "/jekyll-arabic" # المسار الجانبي الخاص بموقعك مثلاً (/blog)
url: "http://tehchieftain.github.io/" # هوستنيم و بروتوكول موقع
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-leap-day